version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/app/node_module
      - .:/home/node/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_module
      - .:/home/node/app
    command: ["npm", "run", "test"]